# Generated by Django 4.2.13 on 2025-04-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0003_remove_ruta_ruta_destino_remove_ruta_ruta_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='rutas.ruta')),
            ],
        ),
    ]
