# Generated by Django 3.2.25 on 2025-05-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensoresRuta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorruta',
            name='place_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
