# Generated by Django 5.1.7 on 2025-03-20 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=255, unique=True)),
                ('licencia', models.CharField(max_length=255, unique=True)),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.horario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
