# Generated by Django 5.1.7 on 2025-03-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255, unique=True)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('capacidad_carga', models.FloatField()),
                ('tipo_vehiculo', models.CharField(max_length=255)),
                ('cumplimiento_normas', models.BooleanField()),
            ],
        ),
    ]
