# Generated by Django 5.1.7 on 2025-03-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calcularenvio', '0006_initial'),
        ('cliente', '0001_initial'),
        ('destinatario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('codigosat', models.CharField(max_length=255)),
                ('noidentificacion', models.CharField(max_length=255)),
                ('codigobarras', models.CharField(blank=True, max_length=255, null=True)),
                ('calculoenvio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcularenvio.calcularenvio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinatario.destinatario')),
            ],
        ),
    ]
