# Generated by Django 5.1.7 on 2025-03-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ubicacion.ubicacion')),
            ],
        ),
    ]
