# Generated by Django 5.1.7 on 2025-03-26 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centrodistribucion', '0001_initial'),
        ('destinatario', '0001_initial'),
        ('paquete', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_id', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('cd_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centrodistribucion.centrodistribucion')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinatario.destinatario')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquete.paquete')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
