# Generated by Django 5.1.7 on 2025-03-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='ruta_id',
        ),
        migrations.AddField(
            model_name='entrega',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='rutas.ruta'),
        ),
    ]
