# Generated by Django 5.1.7 on 2025-03-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0002_remove_entrega_ruta_id_entrega_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='producto',
        ),
    ]
