# Generated by Django 5.1.7 on 2025-03-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0003_remove_entrega_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='ruta',
        ),
    ]
