# Generated by Django 5.1.7 on 2025-04-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0004_remove_entrega_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='cd_destino',
        ),
    ]
