# Generated by Django 5.1.7 on 2025-04-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0005_remove_entrega_cd_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='destinatario',
        ),
    ]
