# Generated by Django 3.2.25 on 2025-05-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='receptor',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
