# Generated by Django 3.2.25 on 2025-05-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20250510_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='nombre',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destinatario',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='remitente',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
