# Generated by Django 5.1.7 on 2025-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinatario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
