# Generated by Django 5.1.7 on 2025-04-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinatario', '0002_destinatario_latitud_destinatario_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatario',
            name='pin',
        ),
    ]
