# Generated by Django 5.1.7 on 2025-03-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
