# Generated by Django 5.1.7 on 2025-04-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='fecha_estimada_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
