# Generated by Django 5.1.7 on 2025-04-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0002_paquete_fecha_estimada_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='fecha_estimada_entrega',
        ),
    ]
