# Generated by Django 5.1.7 on 2025-03-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camiones', '0001_initial'),
        ('chofer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_origen', models.CharField(max_length=255)),
                ('ruta_destino', models.CharField(max_length=255)),
                ('distancia', models.FloatField()),
                ('prioridad', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(default='por hacer', max_length=50)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chofer.chofer')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camiones.camion')),
            ],
        ),
    ]
