# Generated by Django 5.1.7 on 2025-03-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_ruta_entregas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='ruta_destino',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='ruta_origen',
        ),
    ]
