# Generated by Django 4.2.13 on 2025-04-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0006_remove_entrega_destinatario'),
        ('rutas', '0003_remove_ruta_ruta_destino_remove_ruta_ruta_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='entregas',
        ),
        migrations.AddField(
            model_name='ruta',
            name='entregas',
            field=models.ManyToManyField(blank=True, related_name='rutas', to='entrega.entrega'),
        ),
    ]
