# Generated by Django 5.1.7 on 2025-03-09 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_minimo', models.IntegerField()),
                ('rango_maximo', models.IntegerField()),
                ('tarifa_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temperatura', to='tipoproductos.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_minimo', models.IntegerField()),
                ('rango_maximo', models.IntegerField()),
                ('tarifa_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='humedad', to='tipoproductos.tipoproducto')),
            ],
        ),
    ]
