# Generated by Django 5.1.7 on 2025-03-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ubicacion', '0001_initial'),
        ('centrodistribucion', '0001_initial'),
        ('tipoproductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcularEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_piezas', models.IntegerField()),
                ('dimensiones_largo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensiones_ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensiones_alto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_extra_temperatura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarifa_extra_humedad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trasladoiva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ieps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('tarifa_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_por_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('envio_express', models.BooleanField(default=False)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ubicacion.ubicacion')),
                ('origen_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrodistribucion.centrodistribucion')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoproductos.tipoproducto')),
            ],
        ),
    ]
